/* ====================================================================
 * lsew.h - Master Unified Compatibility Umbrella Header
 * Automatically generated by create_master_header.sh
 * Install to: /usr/local/lse/include/lsecompat.h
 * ==================================================================== */

#ifndef LSEATOMICCOMPAT_MASTER_H
#define LSEATOMICCOMPAT_MASTER_H

/* Only process C/C++ code if we are NOT compiling assembly */
#ifndef __ASSEMBLER__

/* Standard feature macro overrides for GNU / POSIX compatibility */
#ifndef _GNU_SOURCE
#  define _GNU_SOURCE 1
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Individual Modular Compatibility Headers */
#include <lse/atomic_compat.h>

#ifdef __cplusplus
}
#endif

#endif /* !__ASSEMBLER__ */

#endif /* LSEATOMICCOMPAT_MASTER_H */
