/* ====================================================================
 * lsew.h - Master Unified Compatibility Umbrella Header
 * Automatically generated by create_master_header.sh
 * Install to: /usr/local/lse/include/lsecompat.h
 * ==================================================================== */

#ifndef LSEWCOMPAT_MASTER_H
#define LSEWCOMPAT_MASTER_H

/* Standard feature macro overrides for GNU / POSIX compatibility */
#ifndef _GNU_SOURCE
#  define _GNU_SOURCE 1
#endif

/* Individual Modular Compatibility Headers */
#include <lse/mbstowcs_compat.h>
#include <lse/wcsstr_compat.h>
#include <lse/wchar_compat.h>


#endif /* LSEWCOMPAT_MASTER_H */
